---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: make check
      - uses: codecov/codecov-action@v4
        with:
          files: tmp/cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
